-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-06-01 11:16:39 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- CRIAÇÃO DAS TABELAS

CREATE TABLE ARGOS_ALERTAS 
    ( 
     id              INTEGER  NOT NULL , 
     titulo          VARCHAR2 (100 CHAR)  NOT NULL , 
     descricao       CLOB  NOT NULL , 
     nivel_alerta    VARCHAR2 (20 CHAR)  NOT NULL , 
     inicio_vigencia DATE , 
     fim_vigencia    DATE , 
     data_criacao    DATE  NOT NULL , 
     ativo           CHAR (1 CHAR)  NOT NULL , 
     ZONAS_RISCO_id  INTEGER , 
     USUARIOS_id     INTEGER 
    ) 
;

CREATE TABLE ARGOS_ANALISES_RISCO 
    ( 
     id                      INTEGER  NOT NULL , 
     chuva_mm_24h            NUMBER (5,1) , 
     probabilidade_enchente  NUMBER (4,3) , 
     indice_susceptibilidade NUMBER (4,3) , 
     score_final             INTEGER  NOT NULL , 
     nivel_risco             VARCHAR2 (20 CHAR)  NOT NULL , 
     fonte_dados             VARCHAR2 (50 CHAR)  NOT NULL , 
     data_analise            DATE  NOT NULL , 
     ZONAS_RISCO_id          INTEGER , 
     USUARIOS_id             INTEGER 
    ) 
;

CREATE TABLE ARGOS_COMENTARIOS_OCORRENCIA 
    ( 
     id             INTEGER  NOT NULL , 
     mensagem       CLOB  NOT NULL , 
     data_criacao   DATE  NOT NULL , 
     ativo          CHAR (1 CHAR)  NOT NULL , 
     OCORRENCIAS_id INTEGER , 
     USUARIOS_id    INTEGER 
    ) 
;

CREATE TABLE ARGOS_LOGS_ALERTA 
    ( 
     id           INTEGER  NOT NULL , 
     acao         VARCHAR2 (20 CHAR)  NOT NULL , 
     data_criacao DATE  NOT NULL , 
     ALERTAS_id   INTEGER , 
     USUARIOS_id  INTEGER 
    ) 
;

CREATE TABLE ARGOS_OCORRENCIAS 
    ( 
     id                  INTEGER  NOT NULL , 
     titulo              VARCHAR2 (100 CHAR)  NOT NULL , 
     descricao           CLOB  NOT NULL , 
     status              VARCHAR2 (20 CHAR)  NOT NULL , 
     latitude            NUMBER (9,6) , 
     longitude           NUMBER (9,6) , 
     data_criacao        DATE  NOT NULL , 
     data_atualizacao    DATE , 
     resolvido_em        DATE , 
     USUARIOS_id         INTEGER , 
     TIPOS_OCORRENCIA_id INTEGER , 
     ZONAS_RISCO_id      INTEGER 
    ) 
;

CREATE TABLE ARGOS_TIPOS_OCORRENCIA 
    ( 
     id        INTEGER  NOT NULL , 
     nome      VARCHAR2 (50 CHAR)  NOT NULL , 
     descricao CLOB , 
     ativo     CHAR (1 CHAR)  NOT NULL 
    ) 
;

CREATE TABLE ARGOS_USUARIOS 
    ( 
     id           INTEGER  NOT NULL , 
     nome         VARCHAR2 (100 CHAR)  NOT NULL , 
     email        VARCHAR2 (100 CHAR)  NOT NULL , 
     senha        VARCHAR2 (50 CHAR)  NOT NULL , 
     telefone     VARCHAR2 (20 CHAR) , 
     tipo         VARCHAR2 (50 CHAR)  NOT NULL , 
     data_criacao DATE  NOT NULL , 
     ativo        CHAR (1 CHAR)  NOT NULL 
    ) 
;

CREATE TABLE ARGOS_ZONAS_RISCO 
    ( 
     id                      INTEGER  NOT NULL , 
     nome                    VARCHAR2 (100 CHAR)  NOT NULL , 
     cidade                  VARCHAR2 (50 CHAR)  NOT NULL , 
     estado                  CHAR (2 CHAR)  NOT NULL , 
     latitude                NUMBER (9,6)  NOT NULL , 
     longitude               NUMBER (9,6)  NOT NULL , 
     descricao               CLOB , 
     nivel_risco_atual       VARCHAR2 (20 CHAR)  NOT NULL , 
     indice_susceptibilidade NUMBER (4,3) , 
     indice_historico_risco  NUMBER (4,3) , 
     ultima_analise          DATE , 
     ativa                   CHAR (1 CHAR)  NOT NULL , 
     data_criacao            DATE  NOT NULL 
    ) 
;

-- PRIMARY KEYS

ALTER TABLE ARGOS_ALERTAS 
    ADD CONSTRAINT ALERTAS_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_COMENTARIOS_OCORRENCIA 
    ADD CONSTRAINT COMENTARIOS_OCORRENCIA_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_LOGS_ALERTA 
    ADD CONSTRAINT LOGS_ALERTA_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_OCORRENCIAS 
    ADD CONSTRAINT OCORRENCIAS_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_TIPOS_OCORRENCIA 
    ADD CONSTRAINT TIPOS_OCORRENCIA_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_USUARIOS 
    ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( id ) ;

ALTER TABLE ARGOS_ZONAS_RISCO 
    ADD CONSTRAINT ZONAS_RISCO_PK PRIMARY KEY ( id ) ;

-- FOREIGN KEYS

ALTER TABLE ARGOS_ALERTAS 
    ADD CONSTRAINT ALERTAS_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_id
    ) 
    REFERENCES ARGOS_USUARIOS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_ALERTAS 
    ADD CONSTRAINT ALERTAS_ZONAS_FK FOREIGN KEY 
    ( 
     ZONAS_RISCO_id
    ) 
    REFERENCES ARGOS_ZONAS_RISCO 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_id
    ) 
    REFERENCES ARGOS_USUARIOS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_ZONAS_FK FOREIGN KEY 
    ( 
     ZONAS_RISCO_id
    ) 
    REFERENCES ARGOS_ZONAS_RISCO 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_COMENTARIOS_OCORRENCIA 
    ADD CONSTRAINT COMENTARIOS_OCORRENCIAS_FK FOREIGN KEY 
    ( 
     OCORRENCIAS_id
    ) 
    REFERENCES ARGOS_OCORRENCIAS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_COMENTARIOS_OCORRENCIA 
    ADD CONSTRAINT COMENTARIOS_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_id
    ) 
    REFERENCES ARGOS_USUARIOS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_LOGS_ALERTA 
    ADD CONSTRAINT LOGS_ALERTA_FK FOREIGN KEY 
    ( 
     ALERTAS_id
    ) 
    REFERENCES ARGOS_ALERTAS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_LOGS_ALERTA 
    ADD CONSTRAINT LOGS_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_id
    ) 
    REFERENCES ARGOS_USUARIOS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_OCORRENCIAS 
    ADD CONSTRAINT OCORRENCIAS_TIPOS_FK FOREIGN KEY 
    ( 
     TIPOS_OCORRENCIA_id
    ) 
    REFERENCES ARGOS_TIPOS_OCORRENCIA 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_OCORRENCIAS 
    ADD CONSTRAINT OCORRENCIAS_USUARIOS_FK FOREIGN KEY 
    ( 
     USUARIOS_id
    ) 
    REFERENCES ARGOS_USUARIOS 
    ( 
     id
    ) 
;

ALTER TABLE ARGOS_OCORRENCIAS 
    ADD CONSTRAINT OCORRENCIAS_ZONAS_RISCO_FK FOREIGN KEY 
    ( 
     ZONAS_RISCO_id
    ) 
    REFERENCES ARGOS_ZONAS_RISCO 
    ( 
     id
    ) 
;

-- CONSTRAINTS

ALTER TABLE ARGOS_USUARIOS 
    ADD CONSTRAINT USUARIOS_email_UN UNIQUE ( email ) ;

ALTER TABLE ARGOS_ALERTAS 
    ADD CONSTRAINT ALERTAS_CK_1 
    CHECK (ativo IN ('S','N'))
;

ALTER TABLE ARGOS_ALERTAS 
    ADD CONSTRAINT ALERTAS_CK_2 
    CHECK (nivel_alerta IN (
    'BAIXO',
    'MEDIO',
    'ALTO',
    'CRITICO'
))
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_CK_1 
    CHECK (nivel_risco IN (
    'BAIXO',
    'MEDIO',
    'ALTO',
    'CRITICO'
))
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_CK_2 
    CHECK (score_final BETWEEN 0 AND 100)
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_CK_3 
    CHECK (probabilidade_enchente BETWEEN 0 AND 1)
;

ALTER TABLE ARGOS_ANALISES_RISCO 
    ADD CONSTRAINT ANALISES_RISCO_CK_4 
    CHECK (indice_susceptibilidade BETWEEN 0 AND 1)
;

ALTER TABLE ARGOS_COMENTARIOS_OCORRENCIA 
    ADD CONSTRAINT COMENTARIOS_OCORRENCIA_CK_1 
    CHECK (ativo IN ('S','N'))
;

ALTER TABLE ARGOS_LOGS_ALERTA 
    ADD CONSTRAINT LOGS_ALERTA_CK_1 
    CHECK (acao IN (
    'CRIADO',
    'EDITADO',
    'ATIVADO',
    'DESATIVADO',
    'ENCERRADO'
))
;

ALTER TABLE ARGOS_OCORRENCIAS 
    ADD CONSTRAINT OCORRENCIAS_CK_1 
    CHECK (status IN (
    'ABERTA',
    'EM_ANALISE',
    'RESOLVIDA'
))
;

ALTER TABLE ARGOS_OCORRENCIAS
    ADD CONSTRAINT OCORRENCIAS_CK_2
    CHECK (latitude BETWEEN -90 AND 90)
;

ALTER TABLE ARGOS_OCORRENCIAS
    ADD CONSTRAINT OCORRENCIAS_CK_3
    CHECK (longitude BETWEEN -180 AND 180)
;

ALTER TABLE ARGOS_TIPOS_OCORRENCIA 
    ADD CONSTRAINT TIPOS_OCORRENCIA_CK_1 
    CHECK (ativo IN ('S','N'))
;

ALTER TABLE ARGOS_USUARIOS 
    ADD CONSTRAINT USUARIOS_CK_1 
    CHECK (ativo IN ('S','N'))
;

ALTER TABLE ARGOS_USUARIOS 
    ADD CONSTRAINT USUARIOS_CK_2 
    CHECK (tipo IN (
    'CIDADAO',
    'DEFESA_CIVIL',
    'ADMIN'
))
;

ALTER TABLE ARGOS_ZONAS_RISCO 
    ADD CONSTRAINT ZONAS_RISCO_CK_1 
    CHECK (ativa IN ('S','N'))
;

ALTER TABLE ARGOS_ZONAS_RISCO 
    ADD CONSTRAINT ZONAS_RISCO_CK_2 
    CHECK (nivel_risco_atual IN (
    'BAIXO',
    'MEDIO',
    'ALTO',
    'CRITICO'
))
;

ALTER TABLE ARGOS_ZONAS_RISCO
    ADD CONSTRAINT OCORRENCIAS_CK_3
    CHECK (latitude BETWEEN -90 AND 90)
;

ALTER TABLE ARGOS_ZONAS_RISCO
    ADD CONSTRAINT OCORRENCIAS_CK_4
    CHECK (longitude BETWEEN -180 AND 180)
;

-- PROCEDURES
